-- =============================================================================
-- Migration 0006: Journey (Nhật ký hành trình) tables + RLS
-- Security review: nhất quán với pattern rls.sql gốc (auth.role() guards,
-- security definer helper function, không có using(true))
-- =============================================================================

-- Journeys (travel diary)
create table if not exists public.journeys (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  title text not null,
  subtitle text,
  cover_gradient text,
  cover_image text,
  status text default 'active' not null check(status in ('draft','active','completed','archived')),
  hide_skeletons boolean default false not null,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  updated_at timestamp with time zone default timezone('utc', now()) not null
);

-- Journey entries (individual diary entries)
create table if not exists public.journey_entries (
  id bigint generated by default as identity primary key,
  journey_id bigint references public.journeys(id) on delete cascade not null,
  source_trip_id bigint references public.trips(id) on delete set null,
  source_place_id bigint references public.places(id) on delete set null,
  author_id uuid references auth.users on delete cascade not null,
  type text default 'entry' not null check(type in ('entry','checkin','skeleton')),
  title text,
  story text,
  entry_date date not null,
  entry_time time,
  location_name text,
  location_lat numeric,
  location_lng numeric,
  mood text,
  weather text,
  tags text[],
  pros_cons jsonb,
  visibility text default 'private' not null,
  sort_order integer default 0 not null,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  updated_at timestamp with time zone default timezone('utc', now()) not null
);

-- Journey trips (linked trips to a journey)
create table if not exists public.journey_trips (
  id bigint generated by default as identity primary key,
  journey_id bigint references public.journeys(id) on delete cascade not null,
  trip_id bigint references public.trips(id) on delete cascade not null,
  added_at timestamp with time zone default timezone('utc', now()) not null,
  unique(journey_id, trip_id)
);

-- Journey contributors (shared editing)
create table if not exists public.journey_contributors (
  id bigint generated by default as identity primary key,
  journey_id bigint references public.journeys(id) on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  role text default 'viewer' not null check(role in ('owner','editor','viewer')),
  added_at timestamp with time zone default timezone('utc', now()) not null,
  unique(journey_id, user_id)
);

-- Journey share links (token-based public sharing)
create table if not exists public.journey_share_links (
  id bigint generated by default as identity primary key,
  journey_id bigint references public.journeys(id) on delete cascade not null,
  token text unique not null default encode(gen_random_bytes(24), 'hex'),
  share_timeline boolean default true not null,
  share_gallery boolean default true not null,
  share_map boolean default true not null,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  unique(journey_id)
);

-- Journey photos — dedicated table, NOT sharing trip_files
-- (trip_files.trip_id FK would be violated with trip_id=0)
create table if not exists public.journey_photos (
  id bigint generated by default as identity primary key,
  journey_id bigint references public.journeys(id) on delete cascade not null,
  entry_id bigint references public.journey_entries(id) on delete cascade,
  storage_path text,          -- Supabase Storage path (bucket: journey-photos)
  url text,                   -- Public URL cached here
  original_name text,
  mime_type text default 'image/jpeg' not null,
  file_size bigint,
  caption text,
  sort_order integer default 0 not null,
  shared boolean default false not null,
  created_at timestamp with time zone default timezone('utc', now()) not null
);

-- =============================================================================
-- Helper function: can user access this journey?
-- security definer — same pattern as public.can_access_trip() in init.sql
-- avoids RLS recursion on journey_contributors
-- =============================================================================
create or replace function public.can_access_journey(journey_id bigint, user_uuid uuid)
returns boolean security definer as $$
begin
  return exists (
    select 1 from public.journeys j
    where j.id = can_access_journey.journey_id and j.user_id = can_access_journey.user_uuid
  ) or exists (
    select 1 from public.journey_contributors jc
    where jc.journey_id = can_access_journey.journey_id and jc.user_id = can_access_journey.user_uuid
  );
end;
$$ language plpgsql;

-- =============================================================================
-- RLS — enabled on all tables
-- Pattern: auth.role() = 'authenticated' guard (consistent with rls.sql)
-- =============================================================================

alter table public.journeys enable row level security;
alter table public.journey_entries enable row level security;
alter table public.journey_trips enable row level security;
alter table public.journey_contributors enable row level security;
alter table public.journey_share_links enable row level security;
alter table public.journey_photos enable row level security;

-- ── Journeys ──────────────────────────────────────────────────────────────────

-- Owner: full CRUD (mirrors trips policy "Users can delete trips they own")
create policy "Owner can manage journeys"
  on public.journeys for all
  using (auth.role() = 'authenticated' and auth.uid() = user_id);

-- Contributors: read only (mirrors trip_members read access pattern)
create policy "Contributors can read journeys"
  on public.journeys for select
  using (
    auth.role() = 'authenticated' and
    exists (
      select 1 from public.journey_contributors
      where journey_id = id and user_id = auth.uid()
    )
  );

-- ── Journey Entries ───────────────────────────────────────────────────────────

-- Journey owner: manage ALL entries (mirrors "trip owner manages all trip content")
create policy "Journey owner can manage all entries"
  on public.journey_entries for all
  using (
    auth.role() = 'authenticated' and
    exists (select 1 from public.journeys where id = journey_id and user_id = auth.uid())
  );

-- Entry author: manage own entries
create policy "Author can manage own entries"
  on public.journey_entries for all
  using (auth.role() = 'authenticated' and auth.uid() = author_id);

-- All journey members: read entries
create policy "Journey members can read entries"
  on public.journey_entries for select
  using (
    auth.role() = 'authenticated' and
    public.can_access_journey(journey_id, auth.uid())
  );

-- ── Journey Trips ─────────────────────────────────────────────────────────────

create policy "Journey members can read journey_trips"
  on public.journey_trips for select
  using (auth.role() = 'authenticated' and public.can_access_journey(journey_id, auth.uid()));

create policy "Journey owner can manage journey_trips"
  on public.journey_trips for all
  using (
    auth.role() = 'authenticated' and
    exists (select 1 from public.journeys where id = journey_id and user_id = auth.uid())
  );

-- ── Journey Contributors ──────────────────────────────────────────────────────

-- Journey owner: full control over contributor list
create policy "Journey owner can manage contributors"
  on public.journey_contributors for all
  using (
    auth.role() = 'authenticated' and
    exists (select 1 from public.journeys where id = journey_id and user_id = auth.uid())
  );

-- All journey members: see who else is in the journey
create policy "Journey members can read contributor list"
  on public.journey_contributors for select
  using (
    auth.role() = 'authenticated' and
    public.can_access_journey(journey_id, auth.uid())
  );

-- ── Journey Share Links ───────────────────────────────────────────────────────

-- Owner only: manage share links
create policy "Journey owner can manage share links"
  on public.journey_share_links for all
  using (
    auth.role() = 'authenticated' and
    exists (select 1 from public.journeys where id = journey_id and user_id = auth.uid())
  );

-- Authenticated users can read share links (API filters by token before returning to public)
-- Removed using(true) — was exposing entire table to anon users
create policy "Authenticated users can read share links"
  on public.journey_share_links for select
  using (auth.role() = 'authenticated');

-- ── Journey Photos ────────────────────────────────────────────────────────────

-- Journey owner: full CRUD
create policy "Journey owner can manage photos"
  on public.journey_photos for all
  using (
    auth.role() = 'authenticated' and
    exists (select 1 from public.journeys where id = journey_id and user_id = auth.uid())
  );

-- Editors: can also manage photos
create policy "Journey editors can manage photos"
  on public.journey_photos for all
  using (
    auth.role() = 'authenticated' and
    exists (
      select 1 from public.journey_contributors jc
      where jc.journey_id = journey_photos.journey_id
        and jc.user_id = auth.uid()
        and jc.role = 'editor'
    )
  );

-- All journey members: read photos
create policy "Journey members can read photos"
  on public.journey_photos for select
  using (
    auth.role() = 'authenticated' and
    public.can_access_journey(journey_id, auth.uid())
  );

-- =============================================================================
-- Indexes
-- =============================================================================

create index idx_journeys_user_id on public.journeys(user_id);
create index idx_journey_entries_journey_id on public.journey_entries(journey_id);
create index idx_journey_entries_author_id on public.journey_entries(author_id);
create index idx_journey_entries_entry_date on public.journey_entries(entry_date desc);
create index idx_journey_trips_journey_id on public.journey_trips(journey_id);
create index idx_journey_contributors_journey_id on public.journey_contributors(journey_id);
create index idx_journey_contributors_user_id on public.journey_contributors(user_id);
create index idx_journey_photos_entry_id on public.journey_photos(entry_id);
create index idx_journey_photos_journey_id on public.journey_photos(journey_id);
create index idx_journey_share_links_token on public.journey_share_links(token);
