-- Trip share links table
create table if not exists public.trip_share_links (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  token text unique not null default encode(gen_random_bytes(16), 'hex'),
  created_by uuid references auth.users(id) on delete cascade not null,
  share_map boolean not null default true,
  share_bookings boolean not null default true,
  share_packing boolean not null default false,
  share_budget boolean not null default false,
  share_collab boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(trip_id)
);

-- RLS for trip_share_links
alter table public.trip_share_links enable row level security;

-- Trip owner can manage their share links
create policy "Trip owners can manage share links"
  on public.trip_share_links for all
  using (
    exists (
      select 1 from public.trips
      where id = trip_id and user_id = auth.uid()
    )
  );

-- Anyone (including anon) can read share links by token (for public shared trip view)
create policy "Anyone can read share links by token"
  on public.trip_share_links for select
  using (true);
