-- 1. Bổ sung cấu hình ngân hàng vào bảng Profiles để nhận tiền qua VietQR
alter table public.profiles
add column bank_id text,          -- Mã ngân hàng VietQR (ví dụ: 'vcb', 'tcb', 'mbb')
add column bank_account_no text,  -- Số tài khoản ngân hàng
add column bank_account_name text;-- Tên chủ tài khoản ngân hàng

-- 2. Tạo bảng budget_item_members (Thành viên tham gia chia tiền của từng khoản chi tiêu)
create table public.budget_item_members (
  id bigint generated by default as identity primary key,
  budget_item_id bigint references public.budget_items(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  paid integer default 0 not null, -- 1: Đã trả (cho các hình thức chia tiền đặc biệt), 0: Chưa trả
  unique(budget_item_id, user_id)
);

create index idx_budget_item_members_item on public.budget_item_members(budget_item_id);
create index idx_budget_item_members_user on public.budget_item_members(user_id);

-- 3. Tạo bảng budget_item_payers (Thành viên đã thanh toán trước cho từng khoản chi tiêu)
create table public.budget_item_payers (
  id bigint generated by default as identity primary key,
  budget_item_id bigint references public.budget_items(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  amount double precision default 0.0 not null,
  unique(budget_item_id, user_id)
);

create index idx_budget_item_payers_item on public.budget_item_payers(budget_item_id);

-- 4. Tạo bảng budget_settlements (Quản lý các giao dịch trả nợ quyết toán giữa các thành viên)
create table public.budget_settlements (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  from_user_id uuid references auth.users(id) on delete cascade not null, -- Người chuyển khoản trả nợ
  to_user_id uuid references auth.users(id) on delete cascade not null,   -- Người nhận tiền
  amount double precision not null check (amount > 0),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index idx_budget_settlements_trip on public.budget_settlements(trip_id);

-- 5. Bật Row Level Security (RLS) cho tất cả các bảng mới
alter table public.budget_item_members enable row level security;
alter table public.budget_item_payers enable row level security;
alter table public.budget_settlements enable row level security;

-- 6. Tạo chính sách RLS cho budget_item_members
create policy "Users can modify budget item members if they have access to the trip"
  on public.budget_item_members for all
  using (
    auth.role() = 'authenticated' and (
      exists (
        select 1 from public.budget_items bi
        join public.trips t on bi.trip_id = t.id
        where bi.id = budget_item_id and (
          t.user_id = auth.uid() or 
          exists (
            select 1 from public.trip_members tm
            where tm.trip_id = t.id and tm.user_id = auth.uid()
          )
        )
      )
    )
  );

-- 7. Tạo chính sách RLS cho budget_item_payers
create policy "Users can modify budget item payers if they have access to the trip"
  on public.budget_item_payers for all
  using (
    auth.role() = 'authenticated' and (
      exists (
        select 1 from public.budget_items bi
        join public.trips t on bi.trip_id = t.id
        where bi.id = budget_item_id and (
          t.user_id = auth.uid() or 
          exists (
            select 1 from public.trip_members tm
            where tm.trip_id = t.id and tm.user_id = auth.uid()
          )
        )
      )
    )
  );

-- 8. Tạo chính sách RLS cho budget_settlements
create policy "Users can modify budget settlements if they have access to the trip"
  on public.budget_settlements for all
  using (
    auth.role() = 'authenticated' and (
      exists (
        select 1 from public.trips t
        where t.id = trip_id and (
          t.user_id = auth.uid() or 
          exists (
            select 1 from public.trip_members tm
            where tm.trip_id = t.id and tm.user_id = auth.uid()
          )
        )
      )
    )
  );
