-- Tripp Database Schema Initialization for Supabase (PostgreSQL)

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- -----------------------------------------------------------------------------
-- 1. Profiles & Settings
-- -----------------------------------------------------------------------------
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique not null,
  role text not null default 'user',
  maps_api_key text,
  unsplash_api_key text,
  openweather_api_key text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Settings table (key-value pair per user)
create table public.settings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  key text not null,
  value text,
  unique(user_id, key)
);

create table public.app_settings (
  key text primary key,
  value text
);

-- Trigger to automatically create a profile for new auth.users
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    'user'
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- -----------------------------------------------------------------------------
-- 2. Trips & Members
-- -----------------------------------------------------------------------------
create table public.trips (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  title text not null,
  description text,
  start_date date,
  end_date date,
  currency text default 'EUR' not null,
  cover_image text,
  is_archived boolean default false not null,
  reminder_days integer default 3 not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.trip_members (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  invited_by uuid references auth.users,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(trip_id, user_id)
);

create or replace function public.can_access_trip(trip_id bigint, user_uuid uuid)
returns boolean security definer as $$
begin
  return exists (
    select 1 from public.trips t
    where t.id = can_access_trip.trip_id and t.user_id = can_access_trip.user_uuid
  ) or exists (
    select 1 from public.trip_members tm
    where tm.trip_id = can_access_trip.trip_id and tm.user_id = can_access_trip.user_uuid
  );
end;
$$ language plpgsql;

-- -----------------------------------------------------------------------------
-- 3. Days, Categories, Tags, and Places
-- -----------------------------------------------------------------------------
create table public.days (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  day_number integer not null,
  date date,
  notes text,
  title text,
  unique(trip_id, day_number)
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  color text default '#6366f1' not null,
  icon text default '📍' not null,
  user_id uuid references auth.users on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.tags (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  name text not null,
  color text default '#10b981' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.places (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  name text not null,
  description text,
  lat double precision,
  lng double precision,
  address text,
  category_id bigint references public.categories(id) on delete set null,
  price double precision,
  currency text,
  reservation_status text default 'none' not null,
  reservation_notes text,
  reservation_datetime timestamp with time zone,
  place_time time,
  end_time time,
  duration_minutes integer default 60 not null,
  notes text,
  image_url text,
  google_place_id text,
  google_ftid text,
  website text,
  phone text,
  transport_mode text default 'walking' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.place_tags (
  place_id bigint references public.places(id) on delete cascade not null,
  tag_id bigint references public.tags(id) on delete cascade not null,
  primary key (place_id, tag_id)
);

create table public.day_assignments (
  id bigint generated by default as identity primary key,
  day_id bigint references public.days(id) on delete cascade not null,
  place_id bigint references public.places(id) on delete cascade not null,
  order_index integer default 0 not null,
  notes text,
  reservation_status text default 'none' not null,
  reservation_notes text,
  reservation_datetime timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.assignment_participants (
  id bigint generated by default as identity primary key,
  assignment_id bigint references public.day_assignments(id) on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  unique(assignment_id, user_id)
);

create table public.day_notes (
  id bigint generated by default as identity primary key,
  day_id bigint references public.days(id) on delete cascade not null,
  trip_id bigint references public.trips(id) on delete cascade not null,
  text text not null,
  time time,
  icon text default '📝' not null,
  sort_order double precision default 0.0 not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.day_accommodations (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  place_id bigint references public.places(id) on delete set null,
  start_day_id bigint references public.days(id) on delete cascade not null,
  end_day_id bigint references public.days(id) on delete cascade not null,
  check_in timestamp with time zone,
  check_in_end timestamp with time zone,
  check_out timestamp with time zone,
  confirmation text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- -----------------------------------------------------------------------------
-- 4. Budgeting, Packing, and Reservations
-- -----------------------------------------------------------------------------
create table public.budget_items (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  category text default 'Other' not null,
  name text not null,
  total_price double precision default 0.0 not null,
  persons integer,
  days integer,
  note text,
  sort_order integer default 0 not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.packing_items (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  name text not null,
  checked boolean default false not null,
  category text,
  sort_order integer default 0 not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.reservations (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  day_id bigint references public.days(id) on delete set null,
  end_day_id bigint references public.days(id) on delete set null,
  place_id bigint references public.places(id) on delete set null,
  assignment_id bigint references public.day_assignments(id) on delete set null,
  title text not null,
  accommodation_id text,
  reservation_time timestamp with time zone,
  reservation_end_time timestamp with time zone,
  location text,
  confirmation_number text,
  notes text,
  status text default 'pending' not null,
  type text default 'other' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- -----------------------------------------------------------------------------
-- 5. Photos & Files
-- -----------------------------------------------------------------------------
create table public.photos (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  day_id bigint references public.days(id) on delete set null,
  place_id bigint references public.places(id) on delete set null,
  filename text not null,
  original_name text not null,
  file_size bigint,
  mime_type text,
  caption text,
  taken_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.trip_files (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  place_id bigint references public.places(id) on delete set null,
  reservation_id bigint references public.reservations(id) on delete set null,
  filename text not null,
  original_name text not null,
  file_size bigint,
  mime_type text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- -----------------------------------------------------------------------------
-- 6. Collaboration
-- -----------------------------------------------------------------------------
create table public.collab_notes (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  category text default 'General' not null,
  title text not null,
  content text,
  color text default '#6366f1' not null,
  pinned boolean default false not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.collab_polls (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  question text not null,
  options jsonb not null,
  multiple boolean default false not null,
  closed boolean default false not null,
  deadline timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.collab_poll_votes (
  id bigint generated by default as identity primary key,
  poll_id bigint references public.collab_polls(id) on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  option_index integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(poll_id, user_id, option_index)
);

create table public.collab_messages (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  text text not null,
  reply_to bigint references public.collab_messages(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- -----------------------------------------------------------------------------
-- 7. Addons & Providers
-- -----------------------------------------------------------------------------
create table public.addons (
  id text primary key,
  name text not null,
  description text,
  type text default 'global' not null,
  icon text default 'Puzzle' not null,
  enabled boolean default false not null,
  config jsonb default '{}'::jsonb not null,
  sort_order integer default 0 not null
);

create table public.photo_providers (
  id text primary key,
  name text not null,
  description text,
  icon text default 'Image' not null,
  enabled boolean default false not null,
  sort_order integer default 0 not null
);

create table public.photo_provider_fields (
  id bigint generated by default as identity primary key,
  provider_id text references public.photo_providers(id) on delete cascade not null,
  field_key text not null,
  label text not null,
  input_type text default 'text' not null,
  placeholder text,
  hint text,
  required boolean default false not null,
  secret boolean default false not null,
  settings_key text,
  payload_key text,
  sort_order integer default 0 not null,
  unique(provider_id, field_key)
);

-- -----------------------------------------------------------------------------
-- 8. Vacay Addon
-- -----------------------------------------------------------------------------
create table public.vacay_plans (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users on delete cascade not null,
  block_weekends boolean default true not null,
  holidays_enabled boolean default false not null,
  holidays_region text default '' not null,
  company_holidays_enabled boolean default true not null,
  carry_over_enabled boolean default true not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(owner_id)
);

create table public.vacay_plan_members (
  id bigint generated by default as identity primary key,
  plan_id bigint references public.vacay_plans(id) on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  status text default 'pending' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(plan_id, user_id)
);

create table public.vacay_user_colors (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  plan_id bigint references public.vacay_plans(id) on delete cascade not null,
  color text default '#6366f1' not null,
  unique(user_id, plan_id)
);

create table public.vacay_years (
  id bigint generated by default as identity primary key,
  plan_id bigint references public.vacay_plans(id) on delete cascade not null,
  year integer not null,
  unique(plan_id, year)
);

create table public.vacay_user_years (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  plan_id bigint references public.vacay_plans(id) on delete cascade not null,
  year integer not null,
  vacation_days integer default 30 not null,
  carried_over integer default 0 not null,
  unique(user_id, plan_id, year)
);

create table public.vacay_entries (
  id bigint generated by default as identity primary key,
  plan_id bigint references public.vacay_plans(id) on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  date date not null,
  note text default '' not null,
  unique(user_id, plan_id, date)
);

create table public.vacay_company_holidays (
  id bigint generated by default as identity primary key,
  plan_id bigint references public.vacay_plans(id) on delete cascade not null,
  date date not null,
  note text default '' not null,
  unique(plan_id, date)
);

create table public.vacay_holiday_calendars (
  id bigint generated by default as identity primary key,
  plan_id bigint references public.vacay_plans(id) on delete cascade not null,
  region text not null,
  label text,
  color text default '#fecaca' not null,
  sort_order integer default 0 not null
);

-- -----------------------------------------------------------------------------
-- 9. Notifications & Auditing
-- -----------------------------------------------------------------------------
create table public.audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users on delete set null,
  action text not null,
  resource text,
  details text,
  ip text
);

create table public.notifications (
  id bigint generated by default as identity primary key,
  type text not null check(type in ('simple', 'boolean', 'navigate')),
  scope text not null check(scope in ('trip', 'user', 'admin')),
  target bigint not null,
  sender_id uuid references auth.users on delete set null,
  recipient_id uuid references auth.users on delete cascade not null,
  title_key text not null,
  title_params jsonb default '{}'::jsonb not null,
  text_key text not null,
  text_params jsonb default '{}'::jsonb not null,
  positive_text_key text,
  negative_text_key text,
  positive_callback text,
  negative_callback text,
  response text check(response in ('positive', 'negative')),
  navigate_text_key text,
  navigate_target text,
  is_read boolean default false not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.notification_channel_preferences (
  user_id uuid references auth.users on delete cascade not null,
  event_type text not null,
  channel text not null,
  enabled boolean default true not null,
  primary key (user_id, event_type, channel)
);

-- -----------------------------------------------------------------------------
-- 10. Database Indexes
-- -----------------------------------------------------------------------------
create index idx_profiles_username on public.profiles(username);
create index idx_trips_user_id on public.trips(user_id);
create index idx_trip_members_trip_id on public.trip_members(trip_id);
create index idx_trip_members_user_id on public.trip_members(user_id);
create index idx_days_trip_id on public.days(trip_id);
create index idx_places_trip_id on public.places(trip_id);
create index idx_places_category_id on public.places(category_id);
create index idx_day_assignments_day_id on public.day_assignments(day_id);
create index idx_day_assignments_place_id on public.day_assignments(place_id);
create index idx_place_tags_place_id on public.place_tags(place_id);
create index idx_place_tags_tag_id on public.place_tags(tag_id);
create index idx_packing_items_trip_id on public.packing_items(trip_id);
create index idx_budget_items_trip_id on public.budget_items(trip_id);
create index idx_reservations_trip_id on public.reservations(trip_id);
create index idx_day_notes_day_id on public.day_notes(day_id);
create index idx_photos_trip_id on public.photos(trip_id);
create index idx_trip_files_trip_id on public.trip_files(trip_id);
create index idx_collab_notes_trip_id on public.collab_notes(trip_id);
create index idx_collab_polls_trip_id on public.collab_polls(trip_id);
create index idx_collab_messages_trip_id on public.collab_messages(trip_id);
create index idx_notifications_recipient_id_is_read on public.notifications(recipient_id, is_read, created_at desc);
create index idx_audit_log_created_at on public.audit_log(created_at desc);
