-- 1. Bổ sung cấu hình ngân hàng vào bảng Profiles để nhận tiền qua VietQR
alter table public.profiles
add column bank_id text,          -- Mã ngân hàng VietQR (ví dụ: 'vcb', 'tcb', 'mbb')
add column bank_account_no text,  -- Số tài khoản ngân hàng
add column bank_account_name text;-- Tên chủ tài khoản ngân hàng

-- 2. Tạo bảng quản lý giao dịch quyết toán chi phí giữa các thành viên
create table public.budget_settlements (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  from_user_id uuid references auth.users(id) on delete cascade not null, -- Người chuyển tiền
  to_user_id uuid references auth.users(id) on delete cascade not null,   -- Người nhận tiền
  amount double precision not null check (amount > 0),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Bật Row Level Security (RLS)
alter table public.budget_settlements enable row level security;

-- 4. Tạo chính sách RLS cho budget_settlements
create policy "Users can select settlements for trips they have access to"
  on public.budget_settlements for select
  using (
    auth.role() = 'authenticated' and (
      exists (
        select 1 from public.trips t
        where t.id = trip_id and (
          t.user_id = auth.uid() or 
          exists (
            select 1 from public.trip_members tm
            where tm.trip_id = t.id and tm.user_id = auth.uid()
          )
        )
      )
    )
  );

create policy "Users can insert/update/delete settlements for trips they have access to"
  on public.budget_settlements for all
  using (
    auth.role() = 'authenticated' and (
      exists (
        select 1 from public.trips t
        where t.id = trip_id and (
          t.user_id = auth.uid() or 
          exists (
            select 1 from public.trip_members tm
            where tm.trip_id = t.id and tm.user_id = auth.uid()
          )
        )
      )
    )
  );
